/* Generated by Yosys 0.33+6 (git sha1 41b34a193, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1694128612374/work=/usr/local/src/conda/yosys-0.33_7_g41b34a193 -fdebug-prefix-map=/home/david/miniconda3/envs/digital=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

/* hdlname = "\\SQRT" */
/* top =  1  */
/* src = "SQRT.v:1.1-47.10" */
module SQRT(clk, init, rst, A, Q, R, done);
  /* src = "SQRT.v:5.25-5.26" */
  input [7:0] A;
  wire [7:0] A;
  /* src = "SQRT.v:6.26-6.27" */
  output [4:0] Q;
  wire [4:0] Q;
  /* src = "SQRT.v:7.26-7.27" */
  output [8:0] R;
  wire [8:0] R;
  /* src = "SQRT.v:17.24-17.25" */
  wire [5:0] T;
  /* src = "SQRT.v:2.19-2.22" */
  input clk;
  wire clk;
  /* hdlname = "comp20 T" */
  /* src = "SQRT.v:42.19-43.36|comp2.v:2.25-2.26" */
  wire [5:0] \comp20.T ;
  /* hdlname = "comp20 c2" */
  /* src = "SQRT.v:42.19-43.36|comp2.v:3.30-3.32" */
  wire [6:0] \comp20.c2 ;
  /* hdlname = "control_SQRT0 S" */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:5.26-5.27" */
  wire \control_SQRT0.S ;
  /* force_downto = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:16.13-16.19|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:63.22-63.23" */
  /* unused_bits = "1 3 5 7 9" */
  wire [9:0] \control_SQRT0.S_CCU2C_B1_COUT ;
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \control_SQRT0.S_LUT4_D_Z ;
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8" */
  wire \control_SQRT0.S_TRELLIS_FF_Q_DI ;
  /* hdlname = "control_SQRT0 cct" */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:9.31-9.34" */
  wire \control_SQRT0.cct ;
  /* hdlname = "control_SQRT0 clk" */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:2.26-2.29" */
  wire \control_SQRT0.clk ;
  /* hdlname = "control_SQRT0 count" */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:32.10-32.15" */
  wire [3:0] \control_SQRT0.count ;
  wire \control_SQRT0.count_TRELLIS_FF_Q_1_LSR ;
  wire \control_SQRT0.count_TRELLIS_FF_Q_2_LSR ;
  /* force_downto = 32'd1 */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:74.17-74.26|/home/david/miniconda3/envs/digital/bin/../share/yosys/techmap.v:270.23-270.24" */
  wire [3:0] \control_SQRT0.count_TRELLIS_FF_Q_3_DI ;
  wire \control_SQRT0.count_TRELLIS_FF_Q_3_LSR ;
  /* force_downto = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [1:0] \control_SQRT0.count_TRELLIS_FF_Q_CE ;
  /* force_downto = 32'd1 */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:74.17-74.26|/home/david/miniconda3/envs/digital/bin/../share/yosys/techmap.v:270.26-270.27" */
  wire [3:0] \control_SQRT0.count_TRELLIS_FF_Q_DI ;
  wire \control_SQRT0.count_TRELLIS_FF_Q_LSR ;
  /* hdlname = "control_SQRT0 dc" */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:10.31-10.33" */
  wire \control_SQRT0.dc ;
  wire \control_SQRT0.dc_LUT4_D_Z ;
  wire \control_SQRT0.dc_TRELLIS_FF_Q_LSR ;
  /* hdlname = "control_SQRT0 done" */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:13.31-13.35" */
  wire \control_SQRT0.done ;
  /* hdlname = "control_SQRT0 init" */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:4.26-4.30" */
  wire \control_SQRT0.init ;
  /* hdlname = "control_SQRT0 j" */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:6.26-6.27" */
  wire \control_SQRT0.j ;
  /* hdlname = "control_SQRT0 rs" */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:8.31-8.33" */
  wire \control_SQRT0.rs ;
  wire \control_SQRT0.rs_TRELLIS_FF_Q_LSR ;
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \control_SQRT0.rs_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT ;
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \control_SQRT0.rs_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT ;
  /* hdlname = "control_SQRT0 rst" */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:3.26-3.29" */
  wire \control_SQRT0.rst ;
  /* hdlname = "control_SQRT0 s" */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:11.31-11.32" */
  wire \control_SQRT0.s ;
  wire \control_SQRT0.s_TRELLIS_FF_Q_DI ;
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \control_SQRT0.s_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT ;
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \control_SQRT0.s_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT ;
  wire \control_SQRT0.s_TRELLIS_FF_Q_LSR ;
  /* hdlname = "control_SQRT0 sh" */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:12.31-12.33" */
  wire \control_SQRT0.sh ;
  /* hdlname = "control_SQRT0 state" */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:24.11-24.16" */
  wire [3:0] \control_SQRT0.state ;
  /* force_downto = 32'd1 */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:38.7-84.14|control_SQRT.v:0.0-0.0|/home/david/miniconda3/envs/digital/bin/../share/yosys/techmap.v:575.21-575.22" */
  wire [2:0] \control_SQRT0.state_TRELLIS_FF_Q_DI ;
  /* hdlname = "dec0 R" */
  /* src = "SQRT.v:38.17-40.31|dec.v:6.23-6.24" */
  wire [8:0] \dec0.R ;
  /* hdlname = "dec0 S" */
  /* src = "SQRT.v:38.17-40.31|dec.v:7.28-7.29" */
  wire [8:0] \dec0.S ;
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8" */
  wire \dec0.S_TRELLIS_FF_Q_1_DI ;
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8" */
  wire \dec0.S_TRELLIS_FF_Q_2_DI ;
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8" */
  wire \dec0.S_TRELLIS_FF_Q_3_DI ;
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8" */
  wire \dec0.S_TRELLIS_FF_Q_4_DI ;
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8" */
  wire \dec0.S_TRELLIS_FF_Q_5_DI ;
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8" */
  wire \dec0.S_TRELLIS_FF_Q_6_DI ;
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8" */
  wire \dec0.S_TRELLIS_FF_Q_DI ;
  /* hdlname = "dec0 c2" */
  /* src = "SQRT.v:38.17-40.31|dec.v:5.23-5.25" */
  wire [6:0] \dec0.c2 ;
  /* force_downto = 32'd1 */
  /* src = "SQRT.v:42.19-43.36|comp2.v:7.10-7.17|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:32.22-32.23" */
  wire [6:0] \dec0.c2_CCU2C_S0_3_B0 ;
  /* force_downto = 32'd1 */
  /* src = "SQRT.v:42.19-43.36|comp2.v:7.10-7.17|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:63.22-63.23" */
  /* unused_bits = "3 5" */
  wire [7:0] \dec0.c2_CCU2C_S0_3_COUT ;
  /* force_downto = 32'd1 */
  /* src = "SQRT.v:42.19-43.36|comp2.v:7.10-7.17|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:65.22-65.25" */
  /* unused_bits = "1 3 5 6 7" */
  wire [7:0] \dec0.c2_CCU2C_S0_COUT ;
  /* force_downto = 32'd1 */
  /* src = "SQRT.v:42.19-43.36|comp2.v:7.10-7.17|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:65.27-65.29" */
  /* unused_bits = "1 3 5 6 7" */
  wire [7:0] \dec0.c2_CCU2C_S0_S1 ;
  /* hdlname = "dec0 clk" */
  /* src = "SQRT.v:38.17-40.31|dec.v:2.18-2.21" */
  wire \dec0.clk ;
  /* hdlname = "dec0 dc" */
  /* src = "SQRT.v:38.17-40.31|dec.v:4.18-4.20" */
  wire \dec0.dc ;
  /* hdlname = "dec0 rs" */
  /* src = "SQRT.v:38.17-40.31|dec.v:3.18-3.20" */
  wire \dec0.rs ;
  /* src = "SQRT.v:8.20-8.24" */
  output done;
  wire done;
  wire done_TRELLIS_FF_Q_DI;
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire done_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT;
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT;
  /* force_downto = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [4:0] done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z_A;
  wire done_TRELLIS_FF_Q_LSR;
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire done_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT;
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire done_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT;
  /* src = "SQRT.v:3.19-3.23" */
  input init;
  wire init;
  /* force_downto = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [4:0] init_LUT4_B_Z;
  /* hdlname = "lsr0 clk" */
  /* src = "SQRT.v:22.17-24.31|lsr.v:2.18-2.21" */
  wire \lsr0.clk ;
  /* hdlname = "lsr0 i" */
  /* src = "SQRT.v:22.17-24.31|lsr.v:5.23-5.24" */
  wire [7:0] \lsr0.i ;
  /* hdlname = "lsr0 o" */
  /* src = "SQRT.v:22.17-24.31|lsr.v:6.28-6.29" */
  wire [7:0] \lsr0.o ;
  /* src = "SQRT.v:22.17-24.31|lsr.v:9.3-17.8" */
  wire \lsr0.o_TRELLIS_FF_Q_2_DI ;
  /* src = "SQRT.v:22.17-24.31|lsr.v:9.3-17.8" */
  wire \lsr0.o_TRELLIS_FF_Q_3_DI ;
  /* src = "SQRT.v:22.17-24.31|lsr.v:9.3-17.8" */
  wire \lsr0.o_TRELLIS_FF_Q_4_DI ;
  /* src = "SQRT.v:22.17-24.31|lsr.v:9.3-17.8" */
  wire \lsr0.o_TRELLIS_FF_Q_5_DI ;
  /* src = "SQRT.v:22.17-24.31|lsr.v:9.3-17.8" */
  wire \lsr0.o_TRELLIS_FF_Q_6_DI ;
  /* src = "SQRT.v:22.17-24.31|lsr.v:9.3-17.8" */
  wire \lsr0.o_TRELLIS_FF_Q_7_DI ;
  wire \lsr0.o_TRELLIS_FF_Q_CE ;
  wire \lsr0.o_TRELLIS_FF_Q_LSR ;
  /* hdlname = "lsr0 rs" */
  /* src = "SQRT.v:22.17-24.31|lsr.v:3.18-3.20" */
  wire \lsr0.rs ;
  /* hdlname = "lsr0 sh" */
  /* src = "SQRT.v:22.17-24.31|lsr.v:4.18-4.20" */
  wire \lsr0.sh ;
  /* hdlname = "qcct0 Q" */
  /* src = "SQRT.v:26.18-28.31|qcct.v:7.29-7.30" */
  wire [4:0] \qcct0.Q ;
  /* src = "SQRT.v:26.18-28.31|qcct.v:10.3-21.6" */
  wire \qcct0.Q_TRELLIS_FF_Q_1_DI ;
  /* src = "SQRT.v:26.18-28.31|qcct.v:10.3-21.6" */
  wire \qcct0.Q_TRELLIS_FF_Q_2_DI ;
  /* src = "SQRT.v:26.18-28.31|qcct.v:10.3-21.6" */
  wire \qcct0.Q_TRELLIS_FF_Q_3_DI ;
  /* src = "SQRT.v:26.18-28.31|qcct.v:10.3-21.6" */
  wire \qcct0.Q_TRELLIS_FF_Q_4_DI ;
  /* src = "SQRT.v:26.18-28.31|qcct.v:10.3-21.6" */
  wire \qcct0.Q_TRELLIS_FF_Q_DI ;
  /* hdlname = "qcct0 S" */
  /* src = "SQRT.v:26.18-28.31|qcct.v:6.19-6.20" */
  wire \qcct0.S ;
  /* force_downto = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:16.13-16.19|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:65.22-65.25" */
  /* unused_bits = "1 3 5 7 8 9" */
  wire [9:0] \qcct0.S_CCU2C_B0_COUT ;
  /* force_downto = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:16.13-16.19|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:34.26-34.27" */
  wire [8:0] \qcct0.S_CCU2C_B0_S0 ;
  /* force_downto = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:16.13-16.19|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:65.27-65.29" */
  /* unused_bits = "1 3 5 7 8 9" */
  wire [9:0] \qcct0.S_CCU2C_B0_S1 ;
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \qcct0.S_LUT4_D_Z ;
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8" */
  wire \qcct0.S_TRELLIS_FF_Q_DI ;
  /* hdlname = "qcct0 clk" */
  /* src = "SQRT.v:26.18-28.31|qcct.v:2.19-2.22" */
  wire \qcct0.clk ;
  /* hdlname = "qcct0 rs" */
  /* src = "SQRT.v:26.18-28.31|qcct.v:3.19-3.21" */
  wire \qcct0.rs ;
  /* hdlname = "qcct0 sh" */
  /* src = "SQRT.v:26.18-28.31|qcct.v:5.19-5.21" */
  wire \qcct0.sh ;
  /* hdlname = "rcct0 A" */
  /* src = "SQRT.v:30.18-32.31|rcct.v:6.24-6.25" */
  wire [1:0] \rcct0.A ;
  /* hdlname = "rcct0 R" */
  /* src = "SQRT.v:30.18-32.31|rcct.v:8.29-8.30" */
  wire [8:0] \rcct0.R ;
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6" */
  wire \rcct0.R_TRELLIS_FF_Q_1_DI ;
  /* force_downto = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [2:0] \rcct0.R_TRELLIS_FF_Q_1_DI_LUT4_Z_B ;
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6" */
  wire \rcct0.R_TRELLIS_FF_Q_2_DI ;
  /* force_downto = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [2:0] \rcct0.R_TRELLIS_FF_Q_2_DI_LUT4_Z_B ;
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6" */
  wire \rcct0.R_TRELLIS_FF_Q_3_DI ;
  /* force_downto = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [2:0] \rcct0.R_TRELLIS_FF_Q_3_DI_LUT4_Z_B ;
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6" */
  wire \rcct0.R_TRELLIS_FF_Q_4_DI ;
  /* force_downto = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [2:0] \rcct0.R_TRELLIS_FF_Q_4_DI_LUT4_Z_B ;
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6" */
  wire \rcct0.R_TRELLIS_FF_Q_5_DI ;
  /* force_downto = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [2:0] \rcct0.R_TRELLIS_FF_Q_5_DI_LUT4_Z_B ;
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6" */
  wire \rcct0.R_TRELLIS_FF_Q_6_DI ;
  /* force_downto = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [2:0] \rcct0.R_TRELLIS_FF_Q_6_DI_LUT4_Z_B ;
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6" */
  wire \rcct0.R_TRELLIS_FF_Q_7_DI ;
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \rcct0.R_TRELLIS_FF_Q_7_DI_PFUMX_Z_BLUT ;
  wire \rcct0.R_TRELLIS_FF_Q_8_CE ;
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6" */
  wire \rcct0.R_TRELLIS_FF_Q_8_DI ;
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \rcct0.R_TRELLIS_FF_Q_8_DI_PFUMX_Z_BLUT ;
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6" */
  wire \rcct0.R_TRELLIS_FF_Q_DI ;
  /* force_downto = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [2:0] \rcct0.R_TRELLIS_FF_Q_DI_LUT4_Z_B ;
  /* hdlname = "rcct0 S" */
  /* src = "SQRT.v:30.18-32.31|rcct.v:7.24-7.25" */
  wire [8:0] \rcct0.S ;
  /* hdlname = "rcct0 cct" */
  /* src = "SQRT.v:30.18-32.31|rcct.v:4.19-4.22" */
  wire \rcct0.cct ;
  /* hdlname = "rcct0 clk" */
  /* src = "SQRT.v:30.18-32.31|rcct.v:2.19-2.22" */
  wire \rcct0.clk ;
  /* hdlname = "rcct0 rs" */
  /* src = "SQRT.v:30.18-32.31|rcct.v:3.19-3.21" */
  wire \rcct0.rs ;
  /* hdlname = "rcct0 s" */
  /* src = "SQRT.v:30.18-32.31|rcct.v:5.19-5.20" */
  wire \rcct0.s ;
  /* src = "SQRT.v:4.19-4.22" */
  input rst;
  wire rst;
  /* hdlname = "tcct0 Q" */
  /* src = "SQRT.v:34.18-36.33|tcct.v:5.25-5.26" */
  wire [4:0] \tcct0.Q ;
  /* hdlname = "tcct0 T" */
  /* src = "SQRT.v:34.18-36.33|tcct.v:6.30-6.31" */
  wire [5:0] \tcct0.T ;
  /* force_downto = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [1:0] \tcct0.T_TRELLIS_FF_Q_CE ;
  wire \tcct0.T_TRELLIS_FF_Q_LSR ;
  /* hdlname = "tcct0 cct" */
  /* src = "SQRT.v:34.18-36.33|tcct.v:4.19-4.22" */
  wire \tcct0.cct ;
  /* hdlname = "tcct0 clk" */
  /* src = "SQRT.v:34.18-36.33|tcct.v:2.19-2.22" */
  wire \tcct0.clk ;
  /* hdlname = "tcct0 rs" */
  /* src = "SQRT.v:34.18-36.33|tcct.v:3.19-3.21" */
  wire \tcct0.rs ;
  /* src = "SQRT.v:16.24-16.27" */
  wire [7:0] w_A;
  /* src = "SQRT.v:19.24-19.27" */
  wire [8:0] w_S;
  /* src = "SQRT.v:18.24-18.27" */
  wire [6:0] w_T;
  /* src = "SQRT.v:11.18-11.23" */
  wire w_cct;
  /* src = "SQRT.v:12.18-12.22" */
  wire w_dc;
  /* src = "SQRT.v:20.18-20.21" */
  wire w_j;
  /* src = "SQRT.v:10.18-10.22" */
  wire w_rs;
  /* src = "SQRT.v:13.18-13.21" */
  wire w_s;
  /* src = "SQRT.v:14.18-14.22" */
  wire w_sh;
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:16.13-16.19|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control_SQRT0.S_CCU2C_B1  (
    .A0(\dec0.c2 [6]),
    .A1(1'h0),
    .B0(\dec0.S [6]),
    .B1(\control_SQRT0.S ),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control_SQRT0.S_CCU2C_B1_COUT [6]),
    .COUT(\control_SQRT0.S_CCU2C_B1_COUT [8]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\qcct0.S_CCU2C_B0_S0 [6]),
    .S1(\qcct0.S_CCU2C_B0_S0 [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) \control_SQRT0.S_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\control_SQRT0.S ),
    .Z(\control_SQRT0.S_LUT4_D_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \control_SQRT0.S_TRELLIS_FF_Q  (
    .CE(\control_SQRT0.dc_LUT4_D_Z ),
    .CLK(clk),
    .DI(\control_SQRT0.S_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\control_SQRT0.S )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \control_SQRT0.S_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R [7]),
    .C(\qcct0.S_CCU2C_B0_S0 [7]),
    .D(\control_SQRT0.rs ),
    .Z(\control_SQRT0.S_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) \control_SQRT0.cct_LUT4_C  (
    .A(1'h0),
    .B(1'h0),
    .C(\control_SQRT0.cct ),
    .D(\control_SQRT0.rs ),
    .Z(\tcct0.T_TRELLIS_FF_Q_CE [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \control_SQRT0.cct_LUT4_C_1  (
    .A(1'h0),
    .B(1'h0),
    .C(\control_SQRT0.cct ),
    .D(\control_SQRT0.rs ),
    .Z(\tcct0.T_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control_SQRT0.cct_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(done_TRELLIS_FF_Q_DI),
    .LSR(\control_SQRT0.rs_TRELLIS_FF_Q_LSR ),
    .Q(\control_SQRT0.cct )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:34.3-86.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control_SQRT0.count_TRELLIS_FF_Q  (
    .CE(\control_SQRT0.count_TRELLIS_FF_Q_CE [1]),
    .CLK(clk),
    .DI(\control_SQRT0.count_TRELLIS_FF_Q_DI [3]),
    .LSR(\control_SQRT0.count_TRELLIS_FF_Q_LSR ),
    .Q(\control_SQRT0.count [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:34.3-86.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control_SQRT0.count_TRELLIS_FF_Q_1  (
    .CE(\control_SQRT0.count_TRELLIS_FF_Q_CE [1]),
    .CLK(clk),
    .DI(\control_SQRT0.count_TRELLIS_FF_Q_DI [2]),
    .LSR(\control_SQRT0.count_TRELLIS_FF_Q_1_LSR ),
    .Q(\control_SQRT0.count [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \control_SQRT0.count_TRELLIS_FF_Q_1_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(init_LUT4_B_Z[1]),
    .D(\control_SQRT0.count_TRELLIS_FF_Q_CE [1]),
    .Z(\control_SQRT0.count_TRELLIS_FF_Q_1_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:34.3-86.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control_SQRT0.count_TRELLIS_FF_Q_2  (
    .CE(\control_SQRT0.count_TRELLIS_FF_Q_CE [1]),
    .CLK(clk),
    .DI(\control_SQRT0.count_TRELLIS_FF_Q_DI [1]),
    .LSR(\control_SQRT0.count_TRELLIS_FF_Q_2_LSR ),
    .Q(\control_SQRT0.count [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \control_SQRT0.count_TRELLIS_FF_Q_2_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(init_LUT4_B_Z[1]),
    .D(\control_SQRT0.count_TRELLIS_FF_Q_CE [1]),
    .Z(\control_SQRT0.count_TRELLIS_FF_Q_2_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:34.3-86.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control_SQRT0.count_TRELLIS_FF_Q_3  (
    .CE(\control_SQRT0.count_TRELLIS_FF_Q_CE [1]),
    .CLK(clk),
    .DI(\control_SQRT0.count_TRELLIS_FF_Q_3_DI [0]),
    .LSR(\control_SQRT0.count_TRELLIS_FF_Q_3_LSR ),
    .Q(\control_SQRT0.count [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \control_SQRT0.count_TRELLIS_FF_Q_3_DI_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\control_SQRT0.count [0]),
    .Z(\control_SQRT0.count_TRELLIS_FF_Q_3_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \control_SQRT0.count_TRELLIS_FF_Q_3_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(init_LUT4_B_Z[1]),
    .D(\control_SQRT0.count_TRELLIS_FF_Q_CE [1]),
    .Z(\control_SQRT0.count_TRELLIS_FF_Q_3_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3fc0)
  ) \control_SQRT0.count_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(\control_SQRT0.count [0]),
    .C(\control_SQRT0.count [1]),
    .D(\control_SQRT0.count [2]),
    .Z(\control_SQRT0.count_TRELLIS_FF_Q_DI [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0ff0)
  ) \control_SQRT0.count_TRELLIS_FF_Q_DI_LUT4_Z_1  (
    .A(1'h0),
    .B(1'h0),
    .C(\control_SQRT0.count [0]),
    .D(\control_SQRT0.count [1]),
    .Z(\control_SQRT0.count_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h7f80)
  ) \control_SQRT0.count_TRELLIS_FF_Q_DI_LUT4_Z_2  (
    .A(\control_SQRT0.count [0]),
    .B(\control_SQRT0.count [1]),
    .C(\control_SQRT0.count [2]),
    .D(\control_SQRT0.count [3]),
    .Z(\control_SQRT0.count_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \control_SQRT0.count_TRELLIS_FF_Q_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(init_LUT4_B_Z[1]),
    .D(\control_SQRT0.count_TRELLIS_FF_Q_CE [1]),
    .Z(\control_SQRT0.count_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) \control_SQRT0.dc_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(\control_SQRT0.rs ),
    .D(\control_SQRT0.dc ),
    .Z(\control_SQRT0.dc_LUT4_D_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control_SQRT0.dc_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\control_SQRT0.s_TRELLIS_FF_Q_DI ),
    .LSR(\control_SQRT0.dc_TRELLIS_FF_Q_LSR ),
    .Q(\control_SQRT0.dc )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hfeef)
  ) \control_SQRT0.dc_TRELLIS_FF_Q_LSR_LUT4_Z  (
    .A(\control_SQRT0.state [2]),
    .B(rst),
    .C(\control_SQRT0.state [0]),
    .D(\control_SQRT0.state [1]),
    .Z(\control_SQRT0.dc_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control_SQRT0.rs_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\control_SQRT0.s_TRELLIS_FF_Q_DI ),
    .LSR(\control_SQRT0.rs_TRELLIS_FF_Q_LSR ),
    .Q(\control_SQRT0.rs )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \control_SQRT0.rs_TRELLIS_FF_Q_LSR_PFUMX_Z  (
    .ALUT(\control_SQRT0.rs_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT ),
    .BLUT(\control_SQRT0.rs_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT ),
    .C0(rst),
    .Z(\control_SQRT0.rs_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control_SQRT0.rs_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control_SQRT0.rs_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h73fc)
  ) \control_SQRT0.rs_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT_LUT4_Z  (
    .A(done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z_A[0]),
    .B(\control_SQRT0.state [2]),
    .C(\control_SQRT0.state [0]),
    .D(\control_SQRT0.state [1]),
    .Z(\control_SQRT0.rs_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control_SQRT0.s_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\control_SQRT0.s_TRELLIS_FF_Q_DI ),
    .LSR(\control_SQRT0.s_TRELLIS_FF_Q_LSR ),
    .Q(\control_SQRT0.s )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \control_SQRT0.s_TRELLIS_FF_Q_DI_PFUMX_Z  (
    .ALUT(\control_SQRT0.s_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT ),
    .BLUT(\control_SQRT0.s_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT ),
    .C0(init_LUT4_B_Z[2]),
    .Z(\control_SQRT0.s_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) \control_SQRT0.s_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(rst),
    .Z(\control_SQRT0.s_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hf0fb)
  ) \control_SQRT0.s_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z  (
    .A(done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z_A[0]),
    .B(init_LUT4_B_Z[1]),
    .C(rst),
    .D(init_LUT4_B_Z[3]),
    .Z(\control_SQRT0.s_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'heffb)
  ) \control_SQRT0.s_TRELLIS_FF_Q_LSR_LUT4_Z  (
    .A(rst),
    .B(\control_SQRT0.state [2]),
    .C(\control_SQRT0.state [1]),
    .D(\control_SQRT0.state [0]),
    .Z(\control_SQRT0.s_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) \control_SQRT0.sh_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(\control_SQRT0.rs ),
    .D(\control_SQRT0.sh ),
    .Z(\lsr0.o_TRELLIS_FF_Q_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control_SQRT0.sh_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(done_TRELLIS_FF_Q_DI),
    .LSR(\control_SQRT0.s_TRELLIS_FF_Q_LSR ),
    .Q(\control_SQRT0.sh )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:34.3-86.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control_SQRT0.state_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\control_SQRT0.state_TRELLIS_FF_Q_DI [2]),
    .LSR(rst),
    .Q(\control_SQRT0.state [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:34.3-86.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control_SQRT0.state_TRELLIS_FF_Q_1  (
    .CLK(clk),
    .DI(\control_SQRT0.state_TRELLIS_FF_Q_DI [1]),
    .LSR(rst),
    .Q(\control_SQRT0.state [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:45.26-46.108|control_SQRT.v:34.3-86.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control_SQRT0.state_TRELLIS_FF_Q_2  (
    .CLK(clk),
    .DI(\control_SQRT0.state_TRELLIS_FF_Q_DI [0]),
    .LSR(rst),
    .Q(\control_SQRT0.state [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h70cc)
  ) \control_SQRT0.state_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z_A[0]),
    .B(\control_SQRT0.state [2]),
    .C(\control_SQRT0.state [0]),
    .D(\control_SQRT0.state [1]),
    .Z(\control_SQRT0.state_TRELLIS_FF_Q_DI [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h4f30)
  ) \control_SQRT0.state_TRELLIS_FF_Q_DI_LUT4_Z_1  (
    .A(done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z_A[0]),
    .B(\control_SQRT0.state [2]),
    .C(\control_SQRT0.state [1]),
    .D(\control_SQRT0.state [0]),
    .Z(\control_SQRT0.state_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hfff4)
  ) \control_SQRT0.state_TRELLIS_FF_Q_DI_LUT4_Z_2  (
    .A(done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z_A[0]),
    .B(init_LUT4_B_Z[1]),
    .C(init_LUT4_B_Z[2]),
    .D(init_LUT4_B_Z[3]),
    .Z(\control_SQRT0.state_TRELLIS_FF_Q_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \dec0.S_TRELLIS_FF_Q  (
    .CE(\control_SQRT0.dc_LUT4_D_Z ),
    .CLK(clk),
    .DI(\dec0.S_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\dec0.S [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \dec0.S_TRELLIS_FF_Q_1  (
    .CE(\control_SQRT0.dc_LUT4_D_Z ),
    .CLK(clk),
    .DI(\dec0.S_TRELLIS_FF_Q_1_DI ),
    .LSR(1'h0),
    .Q(\dec0.S [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \dec0.S_TRELLIS_FF_Q_1_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R [5]),
    .C(\qcct0.S_CCU2C_B0_S0 [5]),
    .D(\control_SQRT0.rs ),
    .Z(\dec0.S_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \dec0.S_TRELLIS_FF_Q_2  (
    .CE(\control_SQRT0.dc_LUT4_D_Z ),
    .CLK(clk),
    .DI(\dec0.S_TRELLIS_FF_Q_2_DI ),
    .LSR(1'h0),
    .Q(\dec0.S [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \dec0.S_TRELLIS_FF_Q_2_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R [4]),
    .C(\qcct0.S_CCU2C_B0_S0 [4]),
    .D(\control_SQRT0.rs ),
    .Z(\dec0.S_TRELLIS_FF_Q_2_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \dec0.S_TRELLIS_FF_Q_3  (
    .CE(\control_SQRT0.dc_LUT4_D_Z ),
    .CLK(clk),
    .DI(\dec0.S_TRELLIS_FF_Q_3_DI ),
    .LSR(1'h0),
    .Q(\dec0.S [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \dec0.S_TRELLIS_FF_Q_3_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R [3]),
    .C(\qcct0.S_CCU2C_B0_S0 [3]),
    .D(\control_SQRT0.rs ),
    .Z(\dec0.S_TRELLIS_FF_Q_3_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \dec0.S_TRELLIS_FF_Q_4  (
    .CE(\control_SQRT0.dc_LUT4_D_Z ),
    .CLK(clk),
    .DI(\dec0.S_TRELLIS_FF_Q_4_DI ),
    .LSR(1'h0),
    .Q(\dec0.S [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \dec0.S_TRELLIS_FF_Q_4_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R [2]),
    .C(\qcct0.S_CCU2C_B0_S0 [2]),
    .D(\control_SQRT0.rs ),
    .Z(\dec0.S_TRELLIS_FF_Q_4_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \dec0.S_TRELLIS_FF_Q_5  (
    .CE(\control_SQRT0.dc_LUT4_D_Z ),
    .CLK(clk),
    .DI(\dec0.S_TRELLIS_FF_Q_5_DI ),
    .LSR(1'h0),
    .Q(\dec0.S [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \dec0.S_TRELLIS_FF_Q_5_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R [1]),
    .C(\qcct0.S_CCU2C_B0_S0 [1]),
    .D(\control_SQRT0.rs ),
    .Z(\dec0.S_TRELLIS_FF_Q_5_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \dec0.S_TRELLIS_FF_Q_6  (
    .CE(\control_SQRT0.dc_LUT4_D_Z ),
    .CLK(clk),
    .DI(\dec0.S_TRELLIS_FF_Q_6_DI ),
    .LSR(1'h0),
    .Q(\dec0.S [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \dec0.S_TRELLIS_FF_Q_6_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R [0]),
    .C(\qcct0.S_CCU2C_B0_S0 [0]),
    .D(\control_SQRT0.rs ),
    .Z(\dec0.S_TRELLIS_FF_Q_6_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \dec0.S_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R [6]),
    .C(\qcct0.S_CCU2C_B0_S0 [6]),
    .D(\control_SQRT0.rs ),
    .Z(\dec0.S_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:42.19-43.36|comp2.v:7.10-7.17|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \dec0.c2_CCU2C_S0  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(1'h1),
    .B1(1'h0),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\dec0.c2_CCU2C_S0_3_COUT [7]),
    .COUT(\dec0.c2_CCU2C_S0_COUT [6]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\dec0.c2 [6]),
    .S1(\dec0.c2_CCU2C_S0_S1 [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:42.19-43.36|comp2.v:7.10-7.17|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \dec0.c2_CCU2C_S0_1  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\dec0.c2_CCU2C_S0_3_B0 [4]),
    .B1(\dec0.c2_CCU2C_S0_3_B0 [5]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\dec0.c2_CCU2C_S0_3_COUT [4]),
    .COUT(\dec0.c2_CCU2C_S0_3_COUT [7]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\dec0.c2 [4]),
    .S1(\comp20.c2 [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:42.19-43.36|comp2.v:7.10-7.17|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \dec0.c2_CCU2C_S0_2  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\dec0.c2_CCU2C_S0_3_B0 [2]),
    .B1(\dec0.c2_CCU2C_S0_3_B0 [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\dec0.c2_CCU2C_S0_3_COUT [2]),
    .COUT(\dec0.c2_CCU2C_S0_3_COUT [4]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\dec0.c2 [2]),
    .S1(\comp20.c2 [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:42.19-43.36|comp2.v:7.10-7.17|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \dec0.c2_CCU2C_S0_3  (
    .A0(1'h1),
    .A1(1'h0),
    .B0(\dec0.c2_CCU2C_S0_3_B0 [0]),
    .B1(1'h1),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\dec0.c2_CCU2C_S0_3_COUT [2]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\dec0.c2 [0]),
    .S1(\comp20.c2 [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) done_TRELLIS_FF_Q (
    .CLK(clk),
    .DI(done_TRELLIS_FF_Q_DI),
    .LSR(done_TRELLIS_FF_Q_LSR),
    .Q(done)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX done_TRELLIS_FF_Q_DI_PFUMX_Z (
    .ALUT(done_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT),
    .BLUT(done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT),
    .C0(rst),
    .Z(done_TRELLIS_FF_Q_DI)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) done_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(done_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hfff4)
  ) done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z (
    .A(done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z_A[0]),
    .B(init_LUT4_B_Z[1]),
    .C(init_LUT4_B_Z[2]),
    .D(init_LUT4_B_Z[3]),
    .Z(done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h2aa8)
  ) done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z_A_LUT4_Z (
    .A(\control_SQRT0.count [3]),
    .B(\control_SQRT0.count [1]),
    .C(\control_SQRT0.count [2]),
    .D(\control_SQRT0.count [0]),
    .Z(done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z_A[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX done_TRELLIS_FF_Q_LSR_PFUMX_Z (
    .ALUT(done_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT),
    .BLUT(done_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT),
    .C0(\control_SQRT0.state [0]),
    .Z(done_TRELLIS_FF_Q_LSR)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hf8ff)
  ) done_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT_LUT4_Z (
    .A(done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z_A[0]),
    .B(\control_SQRT0.state [1]),
    .C(rst),
    .D(\control_SQRT0.state [2]),
    .Z(done_TRELLIS_FF_Q_LSR_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) done_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(done_TRELLIS_FF_Q_LSR_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h00fe)
  ) init_LUT4_B (
    .A(\control_SQRT0.state [1]),
    .B(init),
    .C(\control_SQRT0.state [2]),
    .D(\control_SQRT0.state [0]),
    .Z(init_LUT4_B_Z[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3000)
  ) init_LUT4_B_Z_LUT4_Z (
    .A(1'h0),
    .B(\control_SQRT0.state [2]),
    .C(\control_SQRT0.state [1]),
    .D(\control_SQRT0.S ),
    .Z(init_LUT4_B_Z[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hf000)
  ) init_LUT4_B_Z_LUT4_Z_1 (
    .A(1'h0),
    .B(1'h0),
    .C(\control_SQRT0.state [2]),
    .D(\control_SQRT0.state [1]),
    .Z(init_LUT4_B_Z[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:22.17-24.31|lsr.v:9.3-17.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.o_TRELLIS_FF_Q  (
    .CE(\lsr0.o_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A[1]),
    .LSR(\lsr0.o_TRELLIS_FF_Q_LSR ),
    .Q(\lsr0.o [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:22.17-24.31|lsr.v:9.3-17.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.o_TRELLIS_FF_Q_1  (
    .CE(\lsr0.o_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A[0]),
    .LSR(\lsr0.o_TRELLIS_FF_Q_LSR ),
    .Q(\lsr0.o [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:22.17-24.31|lsr.v:9.3-17.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.o_TRELLIS_FF_Q_2  (
    .CE(\lsr0.o_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.o_TRELLIS_FF_Q_2_DI ),
    .LSR(1'h0),
    .Q(\lsr0.o [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \lsr0.o_TRELLIS_FF_Q_2_DI_LUT4_Z  (
    .A(1'h0),
    .B(A[7]),
    .C(\lsr0.o [5]),
    .D(\control_SQRT0.rs ),
    .Z(\lsr0.o_TRELLIS_FF_Q_2_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:22.17-24.31|lsr.v:9.3-17.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.o_TRELLIS_FF_Q_3  (
    .CE(\lsr0.o_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.o_TRELLIS_FF_Q_3_DI ),
    .LSR(1'h0),
    .Q(\lsr0.o [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \lsr0.o_TRELLIS_FF_Q_3_DI_LUT4_Z  (
    .A(1'h0),
    .B(A[6]),
    .C(\lsr0.o [4]),
    .D(\control_SQRT0.rs ),
    .Z(\lsr0.o_TRELLIS_FF_Q_3_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:22.17-24.31|lsr.v:9.3-17.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.o_TRELLIS_FF_Q_4  (
    .CE(\lsr0.o_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.o_TRELLIS_FF_Q_4_DI ),
    .LSR(1'h0),
    .Q(\lsr0.o [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \lsr0.o_TRELLIS_FF_Q_4_DI_LUT4_Z  (
    .A(1'h0),
    .B(A[5]),
    .C(\lsr0.o [3]),
    .D(\control_SQRT0.rs ),
    .Z(\lsr0.o_TRELLIS_FF_Q_4_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:22.17-24.31|lsr.v:9.3-17.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.o_TRELLIS_FF_Q_5  (
    .CE(\lsr0.o_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.o_TRELLIS_FF_Q_5_DI ),
    .LSR(1'h0),
    .Q(\lsr0.o [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \lsr0.o_TRELLIS_FF_Q_5_DI_LUT4_Z  (
    .A(1'h0),
    .B(A[4]),
    .C(\lsr0.o [2]),
    .D(\control_SQRT0.rs ),
    .Z(\lsr0.o_TRELLIS_FF_Q_5_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:22.17-24.31|lsr.v:9.3-17.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.o_TRELLIS_FF_Q_6  (
    .CE(\lsr0.o_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.o_TRELLIS_FF_Q_6_DI ),
    .LSR(1'h0),
    .Q(\lsr0.o [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \lsr0.o_TRELLIS_FF_Q_6_DI_LUT4_Z  (
    .A(1'h0),
    .B(A[3]),
    .C(\lsr0.o [1]),
    .D(\control_SQRT0.rs ),
    .Z(\lsr0.o_TRELLIS_FF_Q_6_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:22.17-24.31|lsr.v:9.3-17.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.o_TRELLIS_FF_Q_7  (
    .CE(\lsr0.o_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr0.o_TRELLIS_FF_Q_7_DI ),
    .LSR(1'h0),
    .Q(\lsr0.o [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \lsr0.o_TRELLIS_FF_Q_7_DI_LUT4_Z  (
    .A(1'h0),
    .B(A[2]),
    .C(\lsr0.o [0]),
    .D(\control_SQRT0.rs ),
    .Z(\lsr0.o_TRELLIS_FF_Q_7_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \lsr0.o_TRELLIS_FF_Q_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\control_SQRT0.rs ),
    .D(\control_SQRT0.sh ),
    .Z(\lsr0.o_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:26.18-28.31|qcct.v:10.3-21.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:6.100-6.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \qcct0.Q_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\qcct0.Q_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\qcct0.Q [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:26.18-28.31|qcct.v:10.3-21.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:6.100-6.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \qcct0.Q_TRELLIS_FF_Q_1  (
    .CLK(clk),
    .DI(\qcct0.Q_TRELLIS_FF_Q_1_DI ),
    .LSR(1'h0),
    .Q(\qcct0.Q [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0a0c)
  ) \qcct0.Q_TRELLIS_FF_Q_1_DI_LUT4_Z  (
    .A(\qcct0.Q [1]),
    .B(\qcct0.Q [2]),
    .C(\control_SQRT0.rs ),
    .D(\control_SQRT0.sh ),
    .Z(\qcct0.Q_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:26.18-28.31|qcct.v:10.3-21.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:6.100-6.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \qcct0.Q_TRELLIS_FF_Q_2  (
    .CLK(clk),
    .DI(\qcct0.Q_TRELLIS_FF_Q_2_DI ),
    .LSR(1'h0),
    .Q(\qcct0.Q [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0a0c)
  ) \qcct0.Q_TRELLIS_FF_Q_2_DI_LUT4_Z  (
    .A(\qcct0.Q [0]),
    .B(\qcct0.Q [1]),
    .C(\control_SQRT0.rs ),
    .D(\control_SQRT0.sh ),
    .Z(\qcct0.Q_TRELLIS_FF_Q_2_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:26.18-28.31|qcct.v:10.3-21.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:6.100-6.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \qcct0.Q_TRELLIS_FF_Q_3  (
    .CLK(clk),
    .DI(\qcct0.Q_TRELLIS_FF_Q_3_DI ),
    .LSR(1'h0),
    .Q(\qcct0.Q [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:26.18-28.31|qcct.v:10.3-21.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \qcct0.Q_TRELLIS_FF_Q_4  (
    .CE(\lsr0.o_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\qcct0.Q_TRELLIS_FF_Q_4_DI ),
    .LSR(1'h0),
    .Q(\qcct0.Q [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3000)
  ) \qcct0.Q_TRELLIS_FF_Q_4_DI_LUT4_Z  (
    .A(1'h0),
    .B(\control_SQRT0.rs ),
    .C(\control_SQRT0.sh ),
    .D(\qcct0.Q [3]),
    .Z(\qcct0.Q_TRELLIS_FF_Q_4_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0a0c)
  ) \qcct0.Q_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(\qcct0.Q [2]),
    .B(\qcct0.Q [3]),
    .C(\control_SQRT0.rs ),
    .D(\control_SQRT0.sh ),
    .Z(\qcct0.Q_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:16.13-16.19|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \qcct0.S_CCU2C_B0  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\qcct0.S ),
    .B1(1'h0),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control_SQRT0.S_CCU2C_B1_COUT [8]),
    .COUT(\qcct0.S_CCU2C_B0_COUT [8]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\qcct0.S_CCU2C_B0_S0 [8]),
    .S1(\qcct0.S_CCU2C_B0_S1 [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:16.13-16.19|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \qcct0.S_CCU2C_B0_S0_CCU2C_S0  (
    .A0(\dec0.c2 [4]),
    .A1(\comp20.c2 [5]),
    .B0(\dec0.S [4]),
    .B1(\dec0.S [5]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control_SQRT0.S_CCU2C_B1_COUT [4]),
    .COUT(\control_SQRT0.S_CCU2C_B1_COUT [6]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\qcct0.S_CCU2C_B0_S0 [4]),
    .S1(\qcct0.S_CCU2C_B0_S0 [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:16.13-16.19|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \qcct0.S_CCU2C_B0_S0_CCU2C_S0_1  (
    .A0(\dec0.c2 [2]),
    .A1(\comp20.c2 [3]),
    .B0(\dec0.S [2]),
    .B1(\dec0.S [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control_SQRT0.S_CCU2C_B1_COUT [2]),
    .COUT(\control_SQRT0.S_CCU2C_B1_COUT [4]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\qcct0.S_CCU2C_B0_S0 [2]),
    .S1(\qcct0.S_CCU2C_B0_S0 [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:16.13-16.19|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \qcct0.S_CCU2C_B0_S0_CCU2C_S0_2  (
    .A0(\dec0.c2 [0]),
    .A1(\comp20.c2 [1]),
    .B0(\dec0.S [0]),
    .B1(\dec0.S [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\control_SQRT0.S_CCU2C_B1_COUT [2]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\qcct0.S_CCU2C_B0_S0 [0]),
    .S1(\qcct0.S_CCU2C_B0_S0 [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hf044)
  ) \qcct0.S_LUT4_C  (
    .A(\control_SQRT0.rs ),
    .B(\qcct0.Q [0]),
    .C(\qcct0.S ),
    .D(\control_SQRT0.sh ),
    .Z(\qcct0.Q_TRELLIS_FF_Q_3_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) \qcct0.S_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\qcct0.S ),
    .Z(\qcct0.S_LUT4_D_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:38.17-40.31|dec.v:11.3-19.8|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \qcct0.S_TRELLIS_FF_Q  (
    .CE(\control_SQRT0.dc_LUT4_D_Z ),
    .CLK(clk),
    .DI(\qcct0.S_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\qcct0.S )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \qcct0.S_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R [8]),
    .C(\qcct0.S_CCU2C_B0_S0 [8]),
    .D(\control_SQRT0.rs ),
    .Z(\qcct0.S_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:6.100-6.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcct0.R_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\rcct0.R_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\rcct0.R [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:6.100-6.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcct0.R_TRELLIS_FF_Q_1  (
    .CLK(clk),
    .DI(\rcct0.R_TRELLIS_FF_Q_1_DI ),
    .LSR(1'h0),
    .Q(\rcct0.R [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hf033)
  ) \rcct0.R_TRELLIS_FF_Q_1_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R_TRELLIS_FF_Q_1_DI_LUT4_Z_B [0]),
    .C(\dec0.S [5]),
    .D(\control_SQRT0.s ),
    .Z(\rcct0.R_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hf5f3)
  ) \rcct0.R_TRELLIS_FF_Q_1_DI_LUT4_Z_B_LUT4_Z  (
    .A(\rcct0.R [3]),
    .B(\rcct0.R [5]),
    .C(\control_SQRT0.rs ),
    .D(\control_SQRT0.cct ),
    .Z(\rcct0.R_TRELLIS_FF_Q_1_DI_LUT4_Z_B [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:6.100-6.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcct0.R_TRELLIS_FF_Q_2  (
    .CLK(clk),
    .DI(\rcct0.R_TRELLIS_FF_Q_2_DI ),
    .LSR(1'h0),
    .Q(\rcct0.R [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hf033)
  ) \rcct0.R_TRELLIS_FF_Q_2_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R_TRELLIS_FF_Q_2_DI_LUT4_Z_B [0]),
    .C(\dec0.S [4]),
    .D(\control_SQRT0.s ),
    .Z(\rcct0.R_TRELLIS_FF_Q_2_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hf5f3)
  ) \rcct0.R_TRELLIS_FF_Q_2_DI_LUT4_Z_B_LUT4_Z  (
    .A(\rcct0.R [2]),
    .B(\rcct0.R [4]),
    .C(\control_SQRT0.rs ),
    .D(\control_SQRT0.cct ),
    .Z(\rcct0.R_TRELLIS_FF_Q_2_DI_LUT4_Z_B [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:6.100-6.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcct0.R_TRELLIS_FF_Q_3  (
    .CLK(clk),
    .DI(\rcct0.R_TRELLIS_FF_Q_3_DI ),
    .LSR(1'h0),
    .Q(\rcct0.R [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hf033)
  ) \rcct0.R_TRELLIS_FF_Q_3_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R_TRELLIS_FF_Q_3_DI_LUT4_Z_B [0]),
    .C(\dec0.S [3]),
    .D(\control_SQRT0.s ),
    .Z(\rcct0.R_TRELLIS_FF_Q_3_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hf5f3)
  ) \rcct0.R_TRELLIS_FF_Q_3_DI_LUT4_Z_B_LUT4_Z  (
    .A(\rcct0.R [1]),
    .B(\rcct0.R [3]),
    .C(\control_SQRT0.rs ),
    .D(\control_SQRT0.cct ),
    .Z(\rcct0.R_TRELLIS_FF_Q_3_DI_LUT4_Z_B [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:6.100-6.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcct0.R_TRELLIS_FF_Q_4  (
    .CLK(clk),
    .DI(\rcct0.R_TRELLIS_FF_Q_4_DI ),
    .LSR(1'h0),
    .Q(\rcct0.R [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hf033)
  ) \rcct0.R_TRELLIS_FF_Q_4_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R_TRELLIS_FF_Q_4_DI_LUT4_Z_B [0]),
    .C(\dec0.S [2]),
    .D(\control_SQRT0.s ),
    .Z(\rcct0.R_TRELLIS_FF_Q_4_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hf5f3)
  ) \rcct0.R_TRELLIS_FF_Q_4_DI_LUT4_Z_B_LUT4_Z  (
    .A(\rcct0.R [0]),
    .B(\rcct0.R [2]),
    .C(\control_SQRT0.rs ),
    .D(\control_SQRT0.cct ),
    .Z(\rcct0.R_TRELLIS_FF_Q_4_DI_LUT4_Z_B [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:6.100-6.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcct0.R_TRELLIS_FF_Q_5  (
    .CLK(clk),
    .DI(\rcct0.R_TRELLIS_FF_Q_5_DI ),
    .LSR(1'h0),
    .Q(\rcct0.R [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hf033)
  ) \rcct0.R_TRELLIS_FF_Q_5_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R_TRELLIS_FF_Q_5_DI_LUT4_Z_B [0]),
    .C(\dec0.S [1]),
    .D(\control_SQRT0.s ),
    .Z(\rcct0.R_TRELLIS_FF_Q_5_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0fbb)
  ) \rcct0.R_TRELLIS_FF_Q_5_DI_LUT4_Z_B_LUT4_Z  (
    .A(\control_SQRT0.rs ),
    .B(\rcct0.R [1]),
    .C(\lsr0.o [7]),
    .D(\control_SQRT0.cct ),
    .Z(\rcct0.R_TRELLIS_FF_Q_5_DI_LUT4_Z_B [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:6.100-6.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcct0.R_TRELLIS_FF_Q_6  (
    .CLK(clk),
    .DI(\rcct0.R_TRELLIS_FF_Q_6_DI ),
    .LSR(1'h0),
    .Q(\rcct0.R [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hf033)
  ) \rcct0.R_TRELLIS_FF_Q_6_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R_TRELLIS_FF_Q_6_DI_LUT4_Z_B [0]),
    .C(\dec0.S [0]),
    .D(\control_SQRT0.s ),
    .Z(\rcct0.R_TRELLIS_FF_Q_6_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0fbb)
  ) \rcct0.R_TRELLIS_FF_Q_6_DI_LUT4_Z_B_LUT4_Z  (
    .A(\control_SQRT0.rs ),
    .B(\rcct0.R [0]),
    .C(\lsr0.o [6]),
    .D(\control_SQRT0.cct ),
    .Z(\rcct0.R_TRELLIS_FF_Q_6_DI_LUT4_Z_B [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcct0.R_TRELLIS_FF_Q_7  (
    .CE(\rcct0.R_TRELLIS_FF_Q_8_CE ),
    .CLK(clk),
    .DI(\rcct0.R_TRELLIS_FF_Q_7_DI ),
    .LSR(1'h0),
    .Q(\rcct0.R [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \rcct0.R_TRELLIS_FF_Q_7_DI_PFUMX_Z  (
    .ALUT(\qcct0.S_LUT4_D_Z ),
    .BLUT(\rcct0.R_TRELLIS_FF_Q_7_DI_PFUMX_Z_BLUT ),
    .C0(\control_SQRT0.s ),
    .Z(\rcct0.R_TRELLIS_FF_Q_7_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h3000)
  ) \rcct0.R_TRELLIS_FF_Q_7_DI_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(\control_SQRT0.rs ),
    .C(\rcct0.R [6]),
    .D(\control_SQRT0.cct ),
    .Z(\rcct0.R_TRELLIS_FF_Q_7_DI_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:30.18-32.31|rcct.v:11.3-20.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcct0.R_TRELLIS_FF_Q_8  (
    .CE(\rcct0.R_TRELLIS_FF_Q_8_CE ),
    .CLK(clk),
    .DI(\rcct0.R_TRELLIS_FF_Q_8_DI ),
    .LSR(1'h0),
    .Q(\rcct0.R [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) \rcct0.R_TRELLIS_FF_Q_8_CE_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\tcct0.T_TRELLIS_FF_Q_CE [0]),
    .D(\control_SQRT0.s ),
    .Z(\rcct0.R_TRELLIS_FF_Q_8_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \rcct0.R_TRELLIS_FF_Q_8_DI_PFUMX_Z  (
    .ALUT(\control_SQRT0.S_LUT4_D_Z ),
    .BLUT(\rcct0.R_TRELLIS_FF_Q_8_DI_PFUMX_Z_BLUT ),
    .C0(\control_SQRT0.s ),
    .Z(\rcct0.R_TRELLIS_FF_Q_8_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h3000)
  ) \rcct0.R_TRELLIS_FF_Q_8_DI_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(\control_SQRT0.rs ),
    .C(\control_SQRT0.cct ),
    .D(\rcct0.R [5]),
    .Z(\rcct0.R_TRELLIS_FF_Q_8_DI_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hf033)
  ) \rcct0.R_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rcct0.R_TRELLIS_FF_Q_DI_LUT4_Z_B [0]),
    .C(\dec0.S [6]),
    .D(\control_SQRT0.s ),
    .Z(\rcct0.R_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hf5f3)
  ) \rcct0.R_TRELLIS_FF_Q_DI_LUT4_Z_B_LUT4_Z  (
    .A(\rcct0.R [4]),
    .B(\rcct0.R [6]),
    .C(\control_SQRT0.rs ),
    .D(\control_SQRT0.cct ),
    .Z(\rcct0.R_TRELLIS_FF_Q_DI_LUT4_Z_B [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h4001)
  ) rst_LUT4_A (
    .A(rst),
    .B(\control_SQRT0.state [0]),
    .C(\control_SQRT0.state [1]),
    .D(\control_SQRT0.state [2]),
    .Z(\control_SQRT0.count_TRELLIS_FF_Q_CE [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \tcct0.T_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\tcct0.T [5]),
    .Z(\dec0.c2_CCU2C_S0_3_B0 [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \tcct0.T_LUT4_D_1  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\tcct0.T [4]),
    .Z(\dec0.c2_CCU2C_S0_3_B0 [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \tcct0.T_LUT4_D_2  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\tcct0.T [3]),
    .Z(\dec0.c2_CCU2C_S0_3_B0 [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \tcct0.T_LUT4_D_3  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\tcct0.T [2]),
    .Z(\dec0.c2_CCU2C_S0_3_B0 [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \tcct0.T_LUT4_D_4  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\tcct0.T [0]),
    .Z(\dec0.c2_CCU2C_S0_3_B0 [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:34.18-36.33|tcct.v:9.3-18.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \tcct0.T_TRELLIS_FF_Q  (
    .CE(\tcct0.T_TRELLIS_FF_Q_CE [0]),
    .CLK(clk),
    .DI(\qcct0.Q [3]),
    .LSR(\tcct0.T_TRELLIS_FF_Q_LSR ),
    .Q(\tcct0.T [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:34.18-36.33|tcct.v:9.3-18.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \tcct0.T_TRELLIS_FF_Q_1  (
    .CE(\tcct0.T_TRELLIS_FF_Q_CE [0]),
    .CLK(clk),
    .DI(\qcct0.Q [2]),
    .LSR(\tcct0.T_TRELLIS_FF_Q_LSR ),
    .Q(\tcct0.T [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:34.18-36.33|tcct.v:9.3-18.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \tcct0.T_TRELLIS_FF_Q_2  (
    .CE(\tcct0.T_TRELLIS_FF_Q_CE [0]),
    .CLK(clk),
    .DI(\qcct0.Q [1]),
    .LSR(\tcct0.T_TRELLIS_FF_Q_LSR ),
    .Q(\tcct0.T [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:34.18-36.33|tcct.v:9.3-18.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \tcct0.T_TRELLIS_FF_Q_3  (
    .CE(\tcct0.T_TRELLIS_FF_Q_CE [0]),
    .CLK(clk),
    .DI(\qcct0.Q [0]),
    .LSR(\tcct0.T_TRELLIS_FF_Q_LSR ),
    .Q(\tcct0.T [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "SQRT.v:34.18-36.33|tcct.v:9.3-18.6|/home/david/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \tcct0.T_TRELLIS_FF_Q_4  (
    .CE(\tcct0.T_TRELLIS_FF_Q_CE [0]),
    .CLK(clk),
    .DI(1'h1),
    .LSR(\tcct0.T_TRELLIS_FF_Q_LSR ),
    .Q(\tcct0.T [0])
  );
  assign \rcct0.R_TRELLIS_FF_Q_5_DI_LUT4_Z_B [2:1] = { \control_SQRT0.s , \dec0.S [1] };
  assign \rcct0.R_TRELLIS_FF_Q_3_DI_LUT4_Z_B [2:1] = { \control_SQRT0.s , \dec0.S [3] };
  assign { init_LUT4_B_Z[4], init_LUT4_B_Z[0] } = { rst, done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z_A[0] };
  assign \rcct0.R_TRELLIS_FF_Q_1_DI_LUT4_Z_B [2:1] = { \control_SQRT0.s , \dec0.S [5] };
  assign done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z_A[4:1] = { \control_SQRT0.state [0], \control_SQRT0.state [2], rst, \control_SQRT0.state [1] };
  assign \rcct0.R_TRELLIS_FF_Q_6_DI_LUT4_Z_B [2:1] = { \control_SQRT0.s , \dec0.S [0] };
  assign \rcct0.R_TRELLIS_FF_Q_DI_LUT4_Z_B [2:1] = { \control_SQRT0.s , \dec0.S [6] };
  assign \rcct0.R_TRELLIS_FF_Q_4_DI_LUT4_Z_B [2:1] = { \control_SQRT0.s , \dec0.S [2] };
  assign \control_SQRT0.count_TRELLIS_FF_Q_CE [0] = init_LUT4_B_Z[1];
  assign \tcct0.T_TRELLIS_FF_Q_CE [1] = \control_SQRT0.s ;
  assign \rcct0.R_TRELLIS_FF_Q_2_DI_LUT4_Z_B [2:1] = { \control_SQRT0.s , \dec0.S [4] };
  assign { \dec0.c2_CCU2C_S0_3_B0 [6], \dec0.c2_CCU2C_S0_3_B0 [1] } = 2'h3;
  assign { \dec0.c2_CCU2C_S0_3_COUT [6], \dec0.c2_CCU2C_S0_3_COUT [1:0] } = { \dec0.c2_CCU2C_S0_3_COUT [7], \dec0.c2_CCU2C_S0_3_B0 [0], 1'h0 };
  assign { \dec0.c2_CCU2C_S0_COUT [4], \dec0.c2_CCU2C_S0_COUT [2], \dec0.c2_CCU2C_S0_COUT [0] } = { \dec0.c2_CCU2C_S0_3_COUT [7], \dec0.c2_CCU2C_S0_3_COUT [4], \dec0.c2_CCU2C_S0_3_COUT [2] };
  assign { \dec0.c2_CCU2C_S0_S1 [4], \dec0.c2_CCU2C_S0_S1 [2], \dec0.c2_CCU2C_S0_S1 [0] } = { \comp20.c2 [5], \comp20.c2 [3], \comp20.c2 [1] };
  assign \control_SQRT0.count_TRELLIS_FF_Q_3_DI [3:1] = \control_SQRT0.count [3:1];
  assign \control_SQRT0.count_TRELLIS_FF_Q_DI [0] = \control_SQRT0.count_TRELLIS_FF_Q_3_DI [0];
  assign \control_SQRT0.S_CCU2C_B1_COUT [0] = 1'h0;
  assign { \qcct0.S_CCU2C_B0_COUT [6], \qcct0.S_CCU2C_B0_COUT [4], \qcct0.S_CCU2C_B0_COUT [2], \qcct0.S_CCU2C_B0_COUT [0] } = { \control_SQRT0.S_CCU2C_B1_COUT [8], \control_SQRT0.S_CCU2C_B1_COUT [6], \control_SQRT0.S_CCU2C_B1_COUT [4], \control_SQRT0.S_CCU2C_B1_COUT [2] };
  assign { \qcct0.S_CCU2C_B0_S1 [6], \qcct0.S_CCU2C_B0_S1 [4], \qcct0.S_CCU2C_B0_S1 [2], \qcct0.S_CCU2C_B0_S1 [0] } = { \qcct0.S_CCU2C_B0_S0 [7], \qcct0.S_CCU2C_B0_S0 [5], \qcct0.S_CCU2C_B0_S0 [3], \qcct0.S_CCU2C_B0_S0 [1] };
  assign Q = \qcct0.Q ;
  assign R = \rcct0.R ;
  assign T = { \tcct0.T [5:2], 1'h0, \tcct0.T [0] };
  assign \comp20.T  = { \tcct0.T [5:2], 1'h0, \tcct0.T [0] };
  assign { \comp20.c2 [6], \comp20.c2 [4], \comp20.c2 [2], \comp20.c2 [0] } = { \dec0.c2 [6], \dec0.c2 [4], \dec0.c2 [2], \dec0.c2 [0] };
  assign \control_SQRT0.clk  = clk;
  assign \control_SQRT0.done  = done;
  assign \control_SQRT0.init  = init;
  assign \control_SQRT0.j  = 1'hx;
  assign \control_SQRT0.rst  = rst;
  assign \control_SQRT0.state [3] = 1'h0;
  assign \dec0.R  = \rcct0.R ;
  assign \dec0.S [8:7] = { \qcct0.S , \control_SQRT0.S  };
  assign { \dec0.c2 [5], \dec0.c2 [3], \dec0.c2 [1] } = { \comp20.c2 [5], \comp20.c2 [3], \comp20.c2 [1] };
  assign \dec0.clk  = clk;
  assign \dec0.dc  = \control_SQRT0.dc ;
  assign \dec0.rs  = \control_SQRT0.rs ;
  assign \lsr0.clk  = clk;
  assign \lsr0.i  = A;
  assign \lsr0.rs  = \control_SQRT0.rs ;
  assign \lsr0.sh  = \control_SQRT0.sh ;
  assign \qcct0.clk  = clk;
  assign \qcct0.rs  = \control_SQRT0.rs ;
  assign \qcct0.sh  = \control_SQRT0.sh ;
  assign \rcct0.A  = \lsr0.o [7:6];
  assign \rcct0.S  = { \qcct0.S , \control_SQRT0.S , \dec0.S [6:0] };
  assign \rcct0.cct  = \control_SQRT0.cct ;
  assign \rcct0.clk  = clk;
  assign \rcct0.rs  = \control_SQRT0.rs ;
  assign \rcct0.s  = \control_SQRT0.s ;
  assign \tcct0.Q  = \qcct0.Q ;
  assign \tcct0.T [1] = 1'h0;
  assign \tcct0.cct  = \control_SQRT0.cct ;
  assign \tcct0.clk  = clk;
  assign \tcct0.rs  = \control_SQRT0.rs ;
  assign w_A = \lsr0.o ;
  assign w_S = { \qcct0.S , \control_SQRT0.S , \dec0.S [6:0] };
  assign w_T = { \dec0.c2 [6], \comp20.c2 [5], \dec0.c2 [4], \comp20.c2 [3], \dec0.c2 [2], \comp20.c2 [1], \dec0.c2 [0] };
  assign w_cct = \control_SQRT0.cct ;
  assign w_dc = \control_SQRT0.dc ;
  assign w_j = 1'hx;
  assign w_rs = \control_SQRT0.rs ;
  assign w_s = \control_SQRT0.s ;
  assign w_sh = \control_SQRT0.sh ;
endmodule
